      // href for clickable pictires
      var x = [
      //Real norot
        '<a href="./ReviewOvertimeHtml/HTMLReal/GruntyGunner.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/FlappyAnime.html">', 
        '<a href="./ReviewOvertimeHtml/HTMLReal/NoodleCake.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/EscapeGothicVamp.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/EscapeUnderground.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/DeepUnder.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/LibraryEscape.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/FarmerHouse.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/Pixelolite.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/SplillsAndThrills.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/OneEyedJack.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/Buzzmark.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/Edmonton.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/WakeUpPro.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/ElectricToy.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/WatchFace.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/CocoMobile.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/GPlayPremium.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/EternalJourney.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/HouseOfDoors.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/LakehouseFull.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/GPlayFreemium.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/GPlayPremium2.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/StraySouls.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/LocalRegister.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/SellerMobile.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/BrightNest.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/AnyOption.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/Impossible.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/ForChromeCast.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/KungFuMan.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/AtomicAdd.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/AutoDesk.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/BandsInTown.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/DCSounds.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/PlusFree.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/RedShift.html">',
        '<a href="./ReviewOvertimeHtml/HTMLReal/CFHHGoogfull.html">',

      // Fake norot
        '<a href="./ReviewOvertimeHtml/HTMLFake/CreativeCodeApps.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/AirBalooncs.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/DiscoStack.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/MessyRoom.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/RoyalHaircut.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/CutePonyCares.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/CutePony.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/ArmShooting.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/PunisherShooting.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/SoldierOnDuty.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/Mahjong.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/Rakem.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/MrLudo.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/Cadie.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/GPContainer.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/SpellingBug.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/LiveMaps.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/PiratesLost.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/PiranhaQueen.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/LuxometerThermometer.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/ZoomAndFlash.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/BirthdayCalender.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/CarKeysSimulator.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/FingerLieDetector.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/FaceChanger.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/FunnyJoke.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/LoveCalculator.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/PhotoEditor.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/SpiderPrank.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/StopwatchCountdown.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/VoiceRecorder.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/GPSLiveMaps.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/PadronElectoral.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/DogWhistlePro.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/MusicPlayer.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/BloodPressureScanner.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/BloodPressureDetector.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/BakuNow.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/SatelliteNavigation.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/GPSNavigation.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/Estradaovelha.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/MWCEasy.html">',
        '<a href="./ReviewOvertimeHtml/HTMLFake/CathieApp.html">'

      ];
      
      // src for clickable images
      var y = [
        'src="./images/ReviewOvertime/Real/GruntyGunner.png"',
        'src="./images/ReviewOvertime/Real/FlappyAnime.png"',
        'src="./images/ReviewOvertime/Real/NoodleCake.png"',
        'src="./images/ReviewOvertime/Real/EscapeGothicVamp.png"',
        'src="./images/ReviewOvertime/Real/EscapeUnderground.png"',
        'src="./images/ReviewOvertime/Real/DeepUnder.png"',
        'src="./images/ReviewOvertime/Real/LibraryEscape.png"',
        'src="./images/ReviewOvertime/Real/FarmerHouse.png"',
        'src="./images/ReviewOvertime/Real/Pixelolite.png"',
        'src="./images/ReviewOvertime/Real/SplillsAndThrills.png"',
        'src="./images/ReviewOvertime/Real/OneEyedJack.png"',
        'src="./images/ReviewOvertime/Real/Buzzmark.png"',
        'src="./images/ReviewOvertime/Real/Edmonton.png"',
        'src="./images/ReviewOvertime/Real/WakeUpPro.png"',
        'src="./images/ReviewOvertime/Real/ElectricToy.png"',
        'src="./images/ReviewOvertime/Real/WatchFace.png"',
        'src="./images/ReviewOvertime/Real/CocoMobile.png"',
        'src="./images/ReviewOvertime/Real/GPlayPremium.png"',
        'src="./images/ReviewOvertime/Real/EternalJourney.png"',
        'src="./images/ReviewOvertime/Real/HouseOfDoors.png"',
        'src="./images/ReviewOvertime/Real/LakehouseFull.png"',
        'src="./images/ReviewOvertime/Real/GPlayFreemium.png"',
        'src="./images/ReviewOvertime/Real/GPlayPremium2.png"',
        'src="./images/ReviewOvertime/Real/StraySouls.png"',
        'src="./images/ReviewOvertime/Real/LocalRegister.png"',
        'src="./images/ReviewOvertime/Real/SellerMobile.png"',
        'src="./images/ReviewOvertime/Real/BrightNest.png"',
        'src="./images/ReviewOvertime/Real/AnyOption.png"',
        'src="./images/ReviewOvertime/Real/Impossible.png"',
        'src="./images/ReviewOvertime/Real/ForChromeCast.png"',
        'src="./images/ReviewOvertime/Real/KungFuMan.png"',
        'src="./images/ReviewOvertime/Real/AtomicAdd.png"',
        'src="./images/ReviewOvertime/Real/AutoDesk.png"',
        'src="./images/ReviewOvertime/Real/BandsInTown.png"',
        'src="./images/ReviewOvertime/Real/DCSounds.png"',
        'src="./images/ReviewOvertime/Real/PlusFree.png"',
        'src="./images/ReviewOvertime/Real/RedShift.png"',
        'src="./images/ReviewOvertime/Real/CFHHGoogfull.png"',

        'src="./images/ReviewOvertime/Fake/CreativeCodeApps.png"',
        'src="./images/ReviewOvertime/Fake/AirBalooncs.png"',
        'src="./images/ReviewOvertime/Fake/DiscoStack.png"',
        'src="./images/ReviewOvertime/Fake/MessyRoom.png"',
        'src="./images/ReviewOvertime/Fake/RoyalHaircut.png"',
        'src="./images/ReviewOvertime/Fake/CutePonyCares.png"',
        'src="./images/ReviewOvertime/Fake/CutePony.png"',
        'src="./images/ReviewOvertime/Fake/ArmShooting.png"',
        'src="./images/ReviewOvertime/Fake/PunisherShooting.png"',
        'src="./images/ReviewOvertime/Fake/SoldierOnDuty.png"',
        'src="./images/ReviewOvertime/Fake/Mahjong.png"',
        'src="./images/ReviewOvertime/Fake/Rakem.png"',
        'src="./images/ReviewOvertime/Fake/MrLudo.png"',
        'src="./images/ReviewOvertime/Fake/Cadie.png"',
        'src="./images/ReviewOvertime/Fake/GPContainer.png"',
        'src="./images/ReviewOvertime/Fake/SpellingBug.png"',
        'src="./images/ReviewOvertime/Fake/LiveMaps.png"',
        'src="./images/ReviewOvertime/Fake/PiratesLost.png"',
        'src="./images/ReviewOvertime/Fake/PiranhaQueen.png"',
        'src="./images/ReviewOvertime/Fake/LuxometerThermometer.png"',
        'src="./images/ReviewOvertime/Fake/ZoomAndFlash.png"',
        'src="./images/ReviewOvertime/Fake/BirthdayCalender.png"',
        'src="./images/ReviewOvertime/Fake/CarKeysSimulator.png"',
        'src="./images/ReviewOvertime/Fake/FingerLieDetector.png"',
        'src="./images/ReviewOvertime/Fake/FaceChanger.png"',
        'src="./images/ReviewOvertime/Fake/FunnyJoke.png"',
        'src="./images/ReviewOvertime/Fake/LoveCalculator.png"',
        'src="./images/ReviewOvertime/Fake/PhotoEditor.png"',
        'src="./images/ReviewOvertime/Fake/SpiderPrank.png"',
        'src="./images/ReviewOvertime/Fake/StopwatchCountdown.png"',
        'src="./images/ReviewOvertime/Fake/VoiceRecorder.png"',
        'src="./images/ReviewOvertime/Fake/GPSLiveMaps.png"',
        'src="./images/ReviewOvertime/Fake/PadronElectoral.png"',
        'src="./images/ReviewOvertime/Fake/DogWhistlePro.png"',
        'src="./images/ReviewOvertime/Fake/MusicPlayer.png"',
        'src="./images/ReviewOvertime/Fake/BloodPressureScanner.png"',
        'src="./images/ReviewOvertime/Fake/BloodPressureDetector.png"',
        'src="./images/ReviewOvertime/Fake/BakuNow.png"',
        'src="./images/ReviewOvertime/Fake/SatelliteNavigation.png"',
        'src="./images/ReviewOvertime/Fake/GPSNavigation.png"',
        'src="./images/ReviewOvertime/Fake/Estradaovelha.png"',
        'src="./images/ReviewOvertime/Fake/MWCEasy.png"',
        'src="./images/ReviewOvertime/Fake/CathieApp.png"'

      ];

      $(document).ready(function() {
        for (var i = 0; i < 38; i++) {
          clickImage('.realClickableImage', x[i], y[i]);
        }

        for (var i = 38; i < x.length; i++) {
          clickImage('.fakeClickableImage', x[i], y[i]);
        }

      });

      function clickImage(elem, x , y ) { 

        var el = $(elem);
        el.append( x +
            '<img class="align-self-start mr-3 mb-2 img-thumbnail img-fluid" style="width: 30%;"' + y + 'alt="Generic placeholder image"></a>' 
        ); 
      };
