
    var x = [
    //href REAL
    '<a href="./RatingDistributionHTML/HTMLReal/gruntyGunner.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/flappyAnime.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/noodleCake.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/escapeGothicVamp.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/escapeUnderground.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/deepUnder.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/libraryEscape.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/farmerHouse.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/pixelolite.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/splillsAndThrills.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/sneakyFox.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/buzzmark.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/edmonton.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/wakeUpPro.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/electricToyDig.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/watchFace.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/cocoMobile.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/gPlayPremium.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/eternalJourney.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/houseOfDoors.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/lakehouseFull.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/straySouls.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/localRegister.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/sellerMobile.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/bulkyPix.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/ghostMapper.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/lTheme.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/elevate.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/alertsPro.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/oneNote.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/parentToolKit.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/cpuSaver.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/teamDigital.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/cheatSheet.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/openProject.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/postLet.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/stockGlow.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/fbReader.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/gPlayFreemium.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/brightNest.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/anyOption.html">',
    '<a href="./RatingDistributionHTML/HTMLReal/impossible.html">',
    //href FAKE
    '<a href="./RatingDistributionHTML/HTMLFake/creativeCodeApps.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/airBalooncs.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/discoStack.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/messyRoom.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/royalHaircut.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/cutePonyCares.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/cutePony.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/armShooting.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/punisherShooting.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/soldierOnDuty.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/mahjong.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/rakem.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/mrLudo.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/cadie.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/gpContainer.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/spellingBug.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/liveMaps.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/piratesLost.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/piranhaQueen.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/luxometerThermometer.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/zoomAndFlash.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/birthdayCalender.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/carKeysSimulator.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/lieDetector.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/faceChanger.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/funnyJokes.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/loveCalculator.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/photoEditor.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/spiderPrank.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/stopwatchCountdown.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/voiceRecorder.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/gpsLiveMaps.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/padronElectoral.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/dogWhistle.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/musicPlayer.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/bpScanner.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/bpDetector.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/bakuNow.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/satNav.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/gpsNav.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/estradaovelha.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/mwcEasy.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/cathieApp.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/goodAndroid.html">',
    '<a href="./RatingDistributionHTML/HTMLFake/superDuck.html">'
    ];

    var y = [
    //src REAL
    'src="./images/RatingDistribution/Real/gruntyGunner.png"',
    'src="./images/RatingDistribution/Real/flappyAnime.png"',
    'src="./images/RatingDistribution/Real/noodleCake.png"',
    'src="./images/RatingDistribution/Real/escapeGothicVamp.png"',
    'src="./images/RatingDistribution/Real/escapeUnderground.png"',
    'src="./images/RatingDistribution/Real/deepUnder.png"',
    'src="./images/RatingDistribution/Real/libraryEscape.png"',
    'src="./images/RatingDistribution/Real/farmerHouse.png"',
    'src="./images/RatingDistribution/Real/pixelolite.png"',
    'src="./images/RatingDistribution/Real/splillsAndThrills.png"',
    'src="./images/RatingDistribution/Real/sneakyFox.png"',
    'src="./images/RatingDistribution/Real/buzzmark.png"',
    'src="./images/RatingDistribution/Real/edmonton.png"',
    'src="./images/RatingDistribution/Real/wakeUpPro.png"',
    'src="./images/RatingDistribution/Real/electricToyDig.png"',
    'src="./images/RatingDistribution/Real/watchFace.png"',
    'src="./images/RatingDistribution/Real/cocoMobile.png"',
    'src="./images/RatingDistribution/Real/gPlayPremium.png"',
    'src="./images/RatingDistribution/Real/eternalJourney.png"',
    'src="./images/RatingDistribution/Real/houseOfDoors.png"',
    'src="./images/RatingDistribution/Real/lakehouseFull.png"',
    'src="./images/RatingDistribution/Real/straySouls.png"',
    'src="./images/RatingDistribution/Real/localRegister.png"',
    'src="./images/RatingDistribution/Real/sellerMobile.png"',
    'src="./images/RatingDistribution/Real/bulkyPix.png"',
    'src="./images/RatingDistribution/Real/ghostMapper.png"',
    'src="./images/RatingDistribution/Real/lTheme.png"',
    'src="./images/RatingDistribution/Real/elevate.png"',
    'src="./images/RatingDistribution/Real/alertsPro.png"',
    'src="./images/RatingDistribution/Real/oneNote.png"',
    'src="./images/RatingDistribution/Real/parentToolKit.png"',
    'src="./images/RatingDistribution/Real/cpuSaver.png"',
    'src="./images/RatingDistribution/Real/teamDigital.png"',
    'src="./images/RatingDistribution/Real/cheatSheet.png"',
    'src="./images/RatingDistribution/Real/openProject.png"',
    'src="./images/RatingDistribution/Real/postLet.png"',
    'src="./images/RatingDistribution/Real/stockGlow.png"',
    'src="./images/RatingDistribution/Real/fbReader.png"',
    'src="./images/RatingDistribution/Real/gPlayFreemium.png"',
    'src="./images/RatingDistribution/Real/brightNest.png"',
    'src="./images/RatingDistribution/Real/anyOption.png"',
    'src="./images/RatingDistribution/Real/impossible.png"',
    //src FAKE
    'src="./images/RatingDistribution/Fake/creativeCodeApps.png"',
    'src="./images/RatingDistribution/Fake/airBalooncs.png"',
    'src="./images/RatingDistribution/Fake/discoStack.png"',
    'src="./images/RatingDistribution/Fake/messyRoom.png"',
    'src="./images/RatingDistribution/Fake/royalHaircut.png"',
    'src="./images/RatingDistribution/Fake/cutePonyCares.png"',
    'src="./images/RatingDistribution/Fake/cutePony.png"',
    'src="./images/RatingDistribution/Fake/armShooting.png"',
    'src="./images/RatingDistribution/Fake/punisherShooting.png"',
    'src="./images/RatingDistribution/Fake/soldierOnDuty.png"',
    'src="./images/RatingDistribution/Fake/mahjong.png"',
    'src="./images/RatingDistribution/Fake/rakem.png"',
    'src="./images/RatingDistribution/Fake/mrLudo.png"',
    'src="./images/RatingDistribution/Fake/cadie.png"',
    'src="./images/RatingDistribution/Fake/gpContainer.png"',
    'src="./images/RatingDistribution/Fake/spellingBug.png"',
    'src="./images/RatingDistribution/Fake/liveMaps.png"',
    'src="./images/RatingDistribution/Fake/piratesLost.png"',
    'src="./images/RatingDistribution/Fake/piranhaQueen.png"',
    'src="./images/RatingDistribution/Fake/luxometerThermometer.png"',
    'src="./images/RatingDistribution/Fake/zoomAndFlash.png"',
    'src="./images/RatingDistribution/Fake/birthdayCalender.png"',
    'src="./images/RatingDistribution/Fake/carKeysSimulator.png"',
    'src="./images/RatingDistribution/Fake/lieDetector.png"',
    'src="./images/RatingDistribution/Fake/faceChanger.png"',
    'src="./images/RatingDistribution/Fake/funnyJokes.png"',
    'src="./images/RatingDistribution/Fake/loveCalculator.png"',
    'src="./images/RatingDistribution/Fake/photoEditor.png"',
    'src="./images/RatingDistribution/Fake/spiderPrank.png"',
    'src="./images/RatingDistribution/Fake/stopwatchCountdown.png"',
    'src="./images/RatingDistribution/Fake/voiceRecorder.png"',
    'src="./images/RatingDistribution/Fake/gpsLiveMaps.png"',
    'src="./images/RatingDistribution/Fake/padronElectoral.png"',
    'src="./images/RatingDistribution/Fake/dogWhistle.png"',
    'src="./images/RatingDistribution/Fake/musicPlayer.png"',
    'src="./images/RatingDistribution/Fake/bpScanner.png"',
    'src="./images/RatingDistribution/Fake/bpDetector.png"',
    'src="./images/RatingDistribution/Fake/bakuNow.png"',
    'src="./images/RatingDistribution/Fake/satNav.png"',
    'src="./images/RatingDistribution/Fake/gpsNav.png"',
    'src="./images/RatingDistribution/Fake/estradaovelha.png"',
    'src="./images/RatingDistribution/Fake/mwcEasy.png"',
    'src="./images/RatingDistribution/Fake/cathieApp.png"',
    'src="./images/RatingDistribution/Fake/goodAndroid.png"',
    'src="./images/RatingDistribution/Fake/superDuck.png"'
    ];

    $(document).ready(function(){
      for (var i = 0; i < 42; i++){
        clickImage('.realClickableImage',x[i],y[i]);
      }

      for(var i = 42; i <x.length; i++){
        clickImage('.fakeClickableImage', x[i], y[i]);
      }
    });

    function clickImage (elem, x , y) {
        
      var el = $(elem);
      el.append( x +
          '<img class="align-self-start mr-3 mb-2 img-thumbnail img-fluid" style="width: 30%;"' + y + 'alt="Generic placeholder image"></a>' 
      );


    };